"""
One-time (re-runnable) generator: reads src/data/schools.json (the original git-committed
catalog) and emits supabase/seed.sql - INSERT statements for the `schools` and `prompts` tables.

Run once against a fresh Supabase project after applying supabase/schema.sql:
    python scripts/generate_seed_sql.py

Safe to re-run: seed.sql uses ON CONFLICT DO NOTHING, so re-running it after
seed_source.schools.json changes only adds genuinely new rows - it won't clobber scores you've
already entered in prompt_similarity (that table isn't touched by this script at all).
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHOOLS_JSON = ROOT / "supabase" / "seed_source.schools.json"
OUT_SQL = ROOT / "supabase" / "seed.sql"

WORD_RE = re.compile(r"(\d+)\s*-?\s*words?", re.IGNORECASE)


def parse_word_limit(text: str) -> int | None:
    matches = WORD_RE.findall(text)
    if not matches:
        return None
    return max(int(m) for m in matches)


def slugify(text: str, max_words: int = 6) -> str:
    words = re.findall(r"[a-zA-Z0-9']+", text.lower())[:max_words]
    slug = "-".join(words)
    slug = re.sub(r"[^a-z0-9-]", "", slug)
    return slug[:60] or "prompt"


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    schools = json.loads(SCHOOLS_JSON.read_text(encoding="utf-8"))

    school_lines = []
    prompt_lines = []

    for school in schools:
        school_lines.append(
            "  ({id}, {name}, {platform}, {test_optional}, "
            "{english_p25}, {english_p50}, {english_p75}, "
            "{math_p25}, {math_p50}, {math_p75}, {difficulty}, {importance}, {acceptance_rate})".format(
                id=sql_quote(school["id"]),
                name=sql_quote(school["name"]),
                platform=sql_quote(school["platform"]),
                test_optional=sql_quote(school["testOptional"]),
                english_p25=sql_quote(school["englishP25"]),
                english_p50=sql_quote(school["englishP50"]),
                english_p75=sql_quote(school["englishP75"]),
                math_p25=sql_quote(school["mathP25"]),
                math_p50=sql_quote(school["mathP50"]),
                math_p75=sql_quote(school["mathP75"]),
                difficulty=sql_quote(school["difficulty"]),
                importance=sql_quote(school["importance"]),
                acceptance_rate=sql_quote(school["acceptanceRate"]),
            )
        )

        used_ids: set[str] = set()
        for order, prompt in enumerate(school["prompts"]):
            text = prompt["text"]
            base_id = f"{school['id']}--{slugify(text)}"
            prompt_id = base_id
            suffix = 2
            while prompt_id in used_ids:
                prompt_id = f"{base_id}-{suffix}"
                suffix += 1
            used_ids.add(prompt_id)

            prompt_lines.append(
                "  ({id}, {school_id}, {text}, {word_limit}, {sort_order})".format(
                    id=sql_quote(prompt_id),
                    school_id=sql_quote(school["id"]),
                    text=sql_quote(text),
                    word_limit=sql_quote(parse_word_limit(text)),
                    sort_order=order,
                )
            )

    sql = f"""-- Auto-generated by scripts/generate_seed_sql.py from src/data/schools.json.
-- Run once in the Supabase SQL editor after supabase/schema.sql.
-- Re-running after schools.json changes is safe: existing rows are left alone (ON CONFLICT DO
-- NOTHING), so it only adds genuinely new schools/prompts. It never touches prompt_similarity.

INSERT INTO schools (id, name, platform, test_optional, english_p25, english_p50, english_p75,
  math_p25, math_p50, math_p75, difficulty, importance, acceptance_rate)
VALUES
{",\n".join(school_lines)}
ON CONFLICT (id) DO NOTHING;

INSERT INTO prompts (id, school_id, text, word_limit, sort_order)
VALUES
{",\n".join(prompt_lines)}
ON CONFLICT (id) DO NOTHING;
"""

    OUT_SQL.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUT_SQL} ({len(schools)} schools, {len(prompt_lines)} prompts)")


if __name__ == "__main__":
    main()
